name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.x
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Show Python info
        run: |
          python --version
          which python
          pip --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -e .

      - name: "Sanity: list tree"
        run: |
          ls -R

      - name: Run tests with coverage (verbose output)
        env:
          PYTHONPATH: ${{ github.workspace }}
        run: |
          set -e
          pytest -vv --maxfail=1 --cov=app --cov-branch
          coverage report --fail-under=100
